### ISSUE TITLE
Add support for MultiDiscrete action spaces in MSF

### ISSUE THREAD

**Issue by KonstantinRamthun** [PG642/multi-sample-factory#18]

**Comment by Horrible22232** [comment]
# Experiment from November 01, 2021; Branch: iss18
<b>Command to run Rocket League experiment:</b> ** 

### Results: Tensorboard
[rocket_league_multi_discrete.zip](https://github.com/PG642/multi-sample-factory/files/7455676/rocket_league_multi_discrete.zip)
#### Reward
![chrome_KF2PhS9mXq](https://user-images.githubusercontent.com/24734380/139729996-05a57215-66e3-43e5-adb2-7f758fd9fc16.png)
#### Fps
![chrome_obueWYMjkb](https://user-images.githubusercontent.com/24734380/139730022-9991aa69-befe-4ed7-880d-b66df7d6cc36.png)

### Errors:
None

### Whole log:
[rl_saving_training_multi_discrete.log](https://github.com/PG642/multi-sample-factory/files/7455686/rl_saving_training_multi_discrete.log)
