### ISSUE TITLE
Test von Sample-Factory auf LiDO mit Paraden-Szenario

### ISSUE THREAD

**Issue by KonstantinRamthun** [PG642/multi-sample-factory#2]

**Comment by KonstantinRamthun** [comment]
### Installation mit multi-sample-factory

1. Anaconda installieren
```
wget https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh
bash Anaconda3-2021.05-Linux-x86_64.sh
cd anaconda3
source ~/.bashrc
cd ..
rm Anaconda3-2021.05-Linux-x86_64.sh
```

2. LiDo Module laden
```
module load cmake/3.8.2
module load gcc/9.2.0
module load git/2.30.2
```

3. Multi-Sample-Factory klonen und Umgebung einrichten
```
git clone https://github.com/PG642/multi-sample-factory.git
cd multi-sample-factory
```
Jetzt entweder: `conda env create -f environment.yml` (für genaue Versionen) oder `conda env create -f pip-environment.yml` (für Versionen aus pip Paket)
```
conda activate multi-sample-factory
cd ..
```

4. Cuda laden (wirklich notwendig?)
`module load nvidia/cuda/11.1.1`

5. Pakete für PyTOrch installieren (Auch bei .whl notwendig?)
```
conda install astunparse numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing_extensions future six requests dataclasses
conda install -c pytorch magma-cuda111
```
6. PyTorch installieren (entweder selber bauen (mit dem Code unten) oder .whl aus OneDrive nehmen)
```
git clone --recursive https://github.com/pytorch/pytorch
cd pytorch
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
python setup.py install
```
7. Pfad für LD_LIBRARY_PATH setzen
`export LD_LIBRARY_PATH=/work/user/anaconda3/envs/multi-sample-factory/lib`

**Comment by MarcoMeter** [comment]
Was steht spezielles in der .bashrc?
`source ~/.bashrc`

**Comment by GraV1337y** [comment]
Dort ist durch Conda das Setup für die Shell hinterlegt. Dies bedeutet, dass die Shell auch als Anaconda Prompt verwendet werden kann und wird. So steht anschließend z.B. am Anfang der Zeile der Shell in welcher conda-env man sich gerade befindet.
